--sekwencje:
CREATE SEQUENCE kategoria_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE klient_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE platnosc_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE pracownik_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE rezerwacja_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_stolik START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE zamowienie_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE danie_seq START WITH 1 INCREMENT BY 1;


-- tabela: KATEGORIA_DANIA
CREATE TABLE "KATEGORIA_DANIA" 
   (	"ID_KATEGORII" NUMBER, 
	"NAZWA" VARCHAR2(100) NOT NULL ENABLE, 
	"OPIS" VARCHAR2(255), 
	 PRIMARY KEY ("ID_KATEGORII")
  USING INDEX  ENABLE
   ) ;

-- tabela: DANIE
CREATE TABLE "DANIE" 
   (	"ID_DANIA" NUMBER, 
	"NAZWA" VARCHAR2(100) NOT NULL ENABLE, 
	"OPIS" VARCHAR2(255), 
	"CENA" NUMBER(10,2) DEFAULT 0 NOT NULL ENABLE, 
	"DOSTEPNOSC" NUMBER(1,0) NOT NULL ENABLE, 
	"ID_KATEGORII" NUMBER NOT NULL ENABLE, 
	 PRIMARY KEY ("ID_DANIA")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CHK_DANIE_CENA" CHECK (cena > 0 AND cena < 1000) ENABLE, 
	 CONSTRAINT "CHK_DANIE_DOSTEPNOSC" CHECK (dostepnosc IN (0,1)) ENABLE
   ) ;

ALTER TABLE "DANIE" ADD FOREIGN KEY ("ID_KATEGORII")
	  REFERENCES "KATEGORIA_DANIA" ("ID_KATEGORII") ENABLE;

-- tabela: KLIENT
CREATE TABLE "KLIENT" 
   (	"ID_KLIENTA" NUMBER, 
	"IMIE" VARCHAR2(50) NOT NULL ENABLE, 
	"NAZWISKO" VARCHAR2(50), 
	"TELEFON" VARCHAR2(20) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(100) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID_KLIENTA")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CHK_KLIENT_TELEFON" CHECK (REGEXP_LIKE(telefon, '^[0-9]{9}$')) ENABLE, 
	 CONSTRAINT "CHK_KLIENT_EMAIL" CHECK (
  REGEXP_LIKE(email,
    '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'
  )
) ENABLE, 
	 CONSTRAINT "CHK_KLIENT_IMIE_LETTERS" CHECK (REGEXP_LIKE(imie, '^[A-Za-zĄĆĘŁŃÓŚŹŻąćęłńóśźż]+$')) ENABLE, 
	 CONSTRAINT "CHK_KLIENT_NAZWISKO_LETTERS" CHECK (REGEXP_LIKE(nazwisko, '^[A-Za-zĄĆĘŁŃÓŚŹŻąćęłńóśźż]+$')) ENABLE
   ) ;


-- tabela: STOLIK
CREATE TABLE "STOLIK" 
   (	"ID_STOLIKA" NUMBER, 
	"LICZBA_MIEJSC" NUMBER(3,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID_STOLIKA")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CHK_STOLIK_LICZBA_MIEJSC" CHECK (liczba_miejsc BETWEEN 2 AND 16) ENABLE
   ) ;


-- tabela: PRACOWNIK
CREATE TABLE "PRACOWNIK" 
   (	"ID_PRACOWNIKA" NUMBER, 
	"IMIE" VARCHAR2(50) NOT NULL ENABLE, 
	"NAZWISKO" VARCHAR2(50) NOT NULL ENABLE, 
	"DATA_ZATRUDNIENIA" DATE NOT NULL ENABLE, 
	"PLACA" NUMBER(10,2) DEFAULT 0 NOT NULL ENABLE, 
	"LICZBA_OBSLUZONYCH_ZAMOWIEN" NUMBER(3,0) DEFAULT 0 NOT NULL ENABLE, 
	"NAPIWKI" NUMBER(10,2) DEFAULT 0 NOT NULL ENABLE, 
	"LICZBA_PRZYGOTOWANYCH_DAN" NUMBER(3,0) DEFAULT 0 NOT NULL ENABLE, 
	"STANOWISKO_PRACOWNIKA" VARCHAR2(20) NOT NULL ENABLE, 
	 CHECK (stanowisko_pracownika IN ('Kucharz','Kelner')) ENABLE, 
	 PRIMARY KEY ("ID_PRACOWNIKA")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CHK_PRACOWNIK_PLACA" CHECK (placa >= 500) ENABLE, 
	 CONSTRAINT "CHK_PRACOWNIK_IMIE_LETTERS" CHECK (REGEXP_LIKE(imie, '^[A-Za-zĄĆĘŁŃÓŚŹŻąćęłńóśźż]+$')) ENABLE, 
	 CONSTRAINT "CHK_PRACOWNIK_NAZWISKO_LETTERS" CHECK (REGEXP_LIKE(nazwisko, '^[A-Za-zĄĆĘŁŃÓŚŹŻąćęłńóśźż]+$')) ENABLE, 
	 CONSTRAINT "CHK_PRACOWNIK_NAPIWKI_POSITIVE" CHECK (napiwki >= 0) ENABLE
   ) ;



-- tabela: ZAMOWIENIE
CREATE TABLE "ZAMOWIENIE" 
   (	"ID_ZAMOWIENIA" NUMBER, 
	"DATA_ZAMOWIENIA" DATE NOT NULL ENABLE, 
	"STATUS" VARCHAR2(20) NOT NULL ENABLE, 
	"SUMA" NUMBER(10,2) DEFAULT 0 NOT NULL ENABLE, 
	"PRZYPISANY_KLIENT" NUMBER NOT NULL ENABLE, 
	"PRZYPISANY_STOLIK" NUMBER NOT NULL ENABLE, 
	"PRZYPISANY_KELNER" NUMBER NOT NULL ENABLE, 
	 PRIMARY KEY ("ID_ZAMOWIENIA")
  USING INDEX  ENABLE
   ) ;

ALTER TABLE "ZAMOWIENIE" ADD FOREIGN KEY ("PRZYPISANY_KLIENT")
	  REFERENCES "KLIENT" ("ID_KLIENTA") ENABLE;
ALTER TABLE "ZAMOWIENIE" ADD FOREIGN KEY ("PRZYPISANY_STOLIK")
	  REFERENCES "STOLIK" ("ID_STOLIKA") ENABLE;
ALTER TABLE "ZAMOWIENIE" ADD FOREIGN KEY ("PRZYPISANY_KELNER")
	  REFERENCES "PRACOWNIK" ("ID_PRACOWNIKA") ENABLE;



-- tabela: POZYCJA_ZAMOWIENIA
CREATE TABLE "POZYCJA_ZAMOWIENIA" 
   (	"ID_ZAMOWIENIA" NUMBER NOT NULL ENABLE, 
	"ID_DANIA" NUMBER NOT NULL ENABLE, 
	"ILOSC" NUMBER(3,0) DEFAULT 0 NOT NULL ENABLE, 
	"CENA_JEDNOSTKOWA" NUMBER(10,2) DEFAULT 0 NOT NULL ENABLE, 
	"PRZYPISANY_KUCHARZ" NUMBER NOT NULL ENABLE, 
	 PRIMARY KEY ("ID_ZAMOWIENIA", "ID_DANIA")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CHK_POZYCJA_ILOSC_POSITIVE" CHECK (ilosc > 0) ENABLE, 
	 CONSTRAINT "CHK_POZYCJA_CENA_POSITIVE" CHECK (cena_jednostkowa > 0) ENABLE
   ) ;

ALTER TABLE "POZYCJA_ZAMOWIENIA" ADD FOREIGN KEY ("ID_ZAMOWIENIA")
	  REFERENCES "ZAMOWIENIE" ("ID_ZAMOWIENIA") ENABLE;
ALTER TABLE "POZYCJA_ZAMOWIENIA" ADD FOREIGN KEY ("ID_DANIA")
	  REFERENCES "DANIE" ("ID_DANIA") ENABLE;
ALTER TABLE "POZYCJA_ZAMOWIENIA" ADD FOREIGN KEY ("PRZYPISANY_KUCHARZ")
	  REFERENCES "PRACOWNIK" ("ID_PRACOWNIKA") ENABLE;


-- tabela: PLATNOSC
CREATE TABLE "PLATNOSC" 
   (	"ID_PLATNOSCI" NUMBER, 
	"METODA" VARCHAR2(20) NOT NULL ENABLE, 
	"KWOTA" NUMBER(10,2) DEFAULT 0 NOT NULL ENABLE, 
	"DATA_PLATNOSCI" DATE NOT NULL ENABLE, 
	"PRZYPISANE_ZAMOWIENIE" NUMBER NOT NULL ENABLE, 
	"NAPIWEK" NUMBER(10,2) DEFAULT 0 NOT NULL ENABLE, 
	 PRIMARY KEY ("ID_PLATNOSCI")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CHK_NAPIWEK_POSITIVE" CHECK (napiwek >= 0) ENABLE, 
	 CONSTRAINT "CHK_KWOTA_POSITIVE" CHECK (kwota >= 0) ENABLE
   ) ;

ALTER TABLE "PLATNOSC" ADD FOREIGN KEY ("PRZYPISANE_ZAMOWIENIE")
	  REFERENCES "ZAMOWIENIE" ("ID_ZAMOWIENIA") ENABLE;


-- tabela: REZERWACJA
CREATE TABLE "REZERWACJA" 
   (	"ID_REZERWACJI" NUMBER, 
	"DATA_REZERWACJI" DATE NOT NULL ENABLE, 
	"LICZBA_OSOB" NUMBER(3,0) DEFAULT 0 NOT NULL ENABLE, 
	"PRZYPISANY_KLIENT" NUMBER NOT NULL ENABLE, 
	"PRZYPISANY_STOLIK" NUMBER NOT NULL ENABLE, 
	 PRIMARY KEY ("ID_REZERWACJI")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CHK_REZERWACJA_LICZBA_OSOB_POSITIVE" CHECK (liczba_osob > 0) ENABLE
   ) ;

ALTER TABLE "REZERWACJA" ADD FOREIGN KEY ("PRZYPISANY_KLIENT")
	  REFERENCES "KLIENT" ("ID_KLIENTA") ENABLE;
ALTER TABLE "REZERWACJA" ADD FOREIGN KEY ("PRZYPISANY_STOLIK")
	  REFERENCES "STOLIK" ("ID_STOLIKA") ENABLE;


-- trigerry dla tabeli PLATNOSC:
CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_PLATNOSC_BI" 
BEFORE INSERT ON PLATNOSC
FOR EACH ROW
BEGIN
    IF :NEW.id_platnosci IS NULL THEN
        SELECT platnosc_seq.NEXTVAL
        INTO :NEW.id_platnosci
        FROM dual;
    END IF;
    IF :NEW.data_platnosci IS NULL THEN
        :NEW.data_platnosci := SYSDATE;
    END IF;
END;


CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_PLATNOSC_KWOTA" 
BEFORE INSERT ON PLATNOSC
FOR EACH ROW
BEGIN
  SELECT suma
  INTO :NEW.kwota
  FROM zamowienie
  WHERE id_zamowienia = :NEW.przypisane_zamowienie;
END;


CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_PLATNOSC_AFTER_INSERT" 
AFTER INSERT ON PLATNOSC
FOR EACH ROW
BEGIN
    UPDATE zamowienie
    SET status = 'ZREALIZOWANE'
    WHERE id_zamowienia = :NEW.przypisane_zamowienie;
END;


CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_PLATNOSC_KWOTA_CHECK" 
BEFORE INSERT OR UPDATE ON PLATNOSC
FOR EACH ROW
DECLARE
    v_suma NUMBER;
BEGIN
    SELECT suma
    INTO v_suma
    FROM zamowienie
    WHERE id_zamowienia = :NEW.przypisane_zamowienie;

    IF ABS(NVL(:NEW.kwota,0) - NVL(v_suma,0)) > 0.01 THEN
        RAISE_APPLICATION_ERROR(
            -20010,
            'Kwota płatności musi być równa kwocie zamówienia: ' || v_suma || ' zł'
        );
    END IF;
END;


CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_PLATNOSC_NAPIWEK" 
AFTER INSERT ON PLATNOSC
FOR EACH ROW
BEGIN
   IF NVL(:NEW.napiwek, 0) > 0 THEN
      UPDATE pracownik
      SET napiwki = napiwki + :NEW.napiwek
      WHERE id_pracownika = (
          SELECT przypisany_kelner
          FROM zamowienie
          WHERE id_zamowienia = :NEW.przypisane_zamowienie
      );
   END IF;
END;



-- trigerry dla tabeli POZYCJA_ZAMOWIENIA:
CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_POZYCJA_SUMUJ" 
AFTER INSERT OR UPDATE OR DELETE ON POZYCJA_ZAMOWIENIA
FOR EACH ROW
BEGIN
  IF INSERTING THEN
    UPDATE ZAMOWIENIE
    SET SUMA = NVL(SUMA,0) 
             + (:NEW.ILOSC * :NEW.CENA_JEDNOSTKOWA)
    WHERE ID_ZAMOWIENIA = :NEW.ID_ZAMOWIENIA;
  END IF;

  IF UPDATING THEN
    UPDATE ZAMOWIENIE
    SET SUMA = NVL(SUMA,0)
             - (:OLD.ILOSC * :OLD.CENA_JEDNOSTKOWA)
             + (:NEW.ILOSC * :NEW.CENA_JEDNOSTKOWA)
    WHERE ID_ZAMOWIENIA = :NEW.ID_ZAMOWIENIA;
  END IF;

  IF DELETING THEN
    UPDATE ZAMOWIENIE
    SET SUMA = NVL(SUMA,0) 
             - (:OLD.ILOSC * :OLD.CENA_JEDNOSTKOWA)
    WHERE ID_ZAMOWIENIA = :OLD.ID_ZAMOWIENIA;
  END IF;
END;


CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_POZYCJA_SET_OBSLUGIWANE" 
AFTER INSERT ON POZYCJA_ZAMOWIENIA
FOR EACH ROW
BEGIN
   UPDATE zamowienie
   SET status = 'OBSLUGIWANE'
   WHERE id_zamowienia = :NEW.id_zamowienia
     AND status = 'NOWE';
END;


CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_AUTO_CENA" 
BEFORE INSERT OR UPDATE ON POZYCJA_ZAMOWIENIA
FOR EACH ROW
BEGIN
  SELECT cena
  INTO :NEW.cena_jednostkowa
  FROM danie
  WHERE id_dania = :NEW.id_dania;

EXCEPTION
  WHEN NO_DATA_FOUND THEN
    :NEW.cena_jednostkowa := 0;
END;



-- trigerry dla tabeli PRACOWNIK:
CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_PRACOWNIK_BI" 
BEFORE INSERT ON PRACOWNIK
FOR EACH ROW
BEGIN
   IF :NEW.ID_PRACOWNIKA IS NULL THEN
      SELECT pracownik_seq.NEXTVAL
      INTO :NEW.ID_PRACOWNIKA
      FROM dual;
   END IF;
END;


CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_PRACOWNIK_DATA_BI" 
BEFORE INSERT OR UPDATE ON PRACOWNIK
FOR EACH ROW
BEGIN
   IF :NEW.data_zatrudnienia > SYSDATE THEN
      RAISE_APPLICATION_ERROR(-20001, 'Niepoprawna data zatrudnienia!');
   END IF;
END;



-- trigerry dla tabeli REZERWACJA:
CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_REZERWACJA_BI" 
BEFORE INSERT ON REZERWACJA
FOR EACH ROW
BEGIN
  IF :NEW.id_rezerwacji IS NULL THEN
    SELECT rezerwacja_seq.NEXTVAL
    INTO :NEW.id_rezerwacji
    FROM dual;
  END IF;
END;


CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_REZERWACJA_BI_CHECK" 
BEFORE INSERT OR UPDATE ON REZERWACJA
FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN
    IF :NEW.data_rezerwacji < TRUNC(SYSDATE) THEN
        RAISE_APPLICATION_ERROR(-20001, 'Niepoprawna data!');
    END IF;

    SELECT COUNT(*)
    INTO v_count
    FROM rezerwacja
    WHERE przypisany_stolik = :NEW.przypisany_stolik
      AND TRUNC(data_rezerwacji) = TRUNC(:NEW.data_rezerwacji)
      AND id_rezerwacji != NVL(:NEW.id_rezerwacji, 0);

    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'W tym dniu, ten stolik jest już zarezerwowany!');
    END IF;
END;



-- trigerry dla tabeli STOLIK:
CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_STOLIK_BI" 
BEFORE INSERT ON STOLIK
FOR EACH ROW
BEGIN
  IF :NEW.ID_STOLIKA IS NULL THEN
    SELECT seq_stolik.NEXTVAL
    INTO :NEW.ID_STOLIKA
    FROM dual;
  END IF;
END;



-- trigerry dla tabeli KATEGORIA_DANIA:
CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_KATEGORIA_BI" 
BEFORE INSERT ON KATEGORIA_DANIA
FOR EACH ROW
BEGIN
    IF :NEW.ID_KATEGORII IS NULL THEN
        SELECT kategoria_seq.NEXTVAL
        INTO :NEW.ID_KATEGORII
        FROM dual;
    END IF;
END;


-- trigerry dla tabeli ZAMOWIENIE:
CREATE OR REPLACE EDITIONABLE TRIGGER "ZAMOWIENIE_BI" 
BEFORE INSERT ON ZAMOWIENIE
FOR EACH ROW
BEGIN
  IF :NEW.ID_ZAMOWIENIA IS NULL THEN
    SELECT ZAMOWIENIE_SEQ.NEXTVAL
    INTO :NEW.ID_ZAMOWIENIA
    FROM dual;
  END IF;
END;


CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_ZAMOWIENIE_REALIZACJA" 
AFTER UPDATE OF status ON ZAMOWIENIE
FOR EACH ROW
 WHEN (
   OLD.status <> 'ZREALIZOWANE'
   AND NEW.status = 'ZREALIZOWANE'
) BEGIN
   UPDATE PRACOWNIK
   SET liczba_obsluzonych_zamowien =
       liczba_obsluzonych_zamowien + 1
   WHERE id_pracownika = :NEW.przypisany_kelner;

   FOR r IN (
       SELECT przypisany_kucharz,
              SUM(ilosc) suma_dan
       FROM POZYCJA_ZAMOWIENIA
       WHERE id_zamowienia = :NEW.id_zamowienia
       GROUP BY przypisany_kucharz
   )
   LOOP
       UPDATE PRACOWNIK
       SET liczba_przygotowanych_dan =
           liczba_przygotowanych_dan + r.suma_dan
       WHERE id_pracownika = r.przypisany_kucharz;
   END LOOP;

END;


-- trigerry dla tabeli KLIENT:
CREATE OR REPLACE EDITIONABLE TRIGGER "KLIENT_BI" 
BEFORE INSERT ON KLIENT
FOR EACH ROW
BEGIN
  IF :NEW.id_KLIENTA IS NULL THEN
    :NEW.id_KLIENTA := klient_seq.NEXTVAL;
  END IF;
END;



-- trigerry dla tabeli DANIA:
CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_DANIE_BI"
BEFORE INSERT ON DANIE
FOR EACH ROW
BEGIN
  IF :NEW.ID_DANIA IS NULL THEN
    SELECT danie_seq.NEXTVAL
    INTO :NEW.ID_DANIA
    FROM dual;
  END IF;
END;

